language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

script:
    - mkdir /tmp/build
    - platformio ci --project-conf platformio.ini --build-dir="/tmp/build" --keep-build-dir .
before_deploy:
    # Set up git user name and tag this commit
    - git config --local user.name "YOUR GIT USER NAME"
    - git config --local user.email "YOUR GIT USER EMAIL"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG


deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: /tmp/build/.pio/build/**/*
  skip_cleanup: true
  repo: nurikk/test-releases
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|staging|production|dev)$